# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: acmetravel
  pool: 5
  username: root
  password: My123&___
  socket: /var/lib/mysql/mysql.sock

# For exercises also is acmetravel
production: 
  adapter: mysql2
  encoding: utf8
  database: acmetravel_production
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

